from datetime import datetime

SECRET_KEY = 'your-secret-key-here'  # For Flask session security
RECAPTCHA_PUBLIC_KEY = '6Lc7NM8qAAAAACrHqeBqWoP9BM5GLvCG97gJNblZ'  # From Google reCAPTCHA
RECAPTCHA_PRIVATE_KEY = '6Lc7NM8qAAAAAFun1QDCBKSn7YVkTUi8j-wH7qub'  # From Google reCAPTCHA

# NHS Trusts and Specialties lists
NHS_TRUSTS = [
    ('trust1', 'Airedale NHS Foundation Trust'),
    ('trust2', 'Alder Hey Children\'s NHS Foundation Trust'),
    ('trust3', 'Ashford and St Peter\'s Hospitals NHS Foundation Trust'),
    ('trust4', 'Avon and Wiltshire Mental Health Partnership NHS Trust'),
    ('trust5', 'Barking, Havering and Redbridge University Hospitals NHS Trust'),
    ('trust6', 'Barnet, Enfield and Haringey Mental Health NHS Trust'),
    ('trust7', 'Barnsley Hospital NHS Foundation Trust'),
    ('trust8', 'Barts Health NHS Trust'),
    ('trust9', 'Bedfordshire Hospitals NHS Foundation Trust'),
    ('trust10', 'Berkshire Healthcare NHS Foundation Trust'),
    ('trust11', 'Birmingham and Solihull Mental Health NHS Foundation Trust'),
    ('trust12', 'Birmingham Community Healthcare NHS Foundation Trust'),
    ('trust13', 'Birmingham Women\'s and Children\'s NHS Foundation Trust'),
    ('trust14', 'Black Country Partnership NHS Foundation Trust'),
    ('trust15', 'Blackpool Teaching Hospitals NHS Foundation Trust'),
    ('trust16', 'Bolton NHS Foundation Trust'),
    ('trust17', 'Bradford District Care NHS Foundation Trust'),
    ('trust18', 'Bradford Teaching Hospitals NHS Foundation Trust'),
    ('trust19', 'Bridgewater Community Healthcare'),
    ('trust20', 'Buckinghamshire Healthcare NHS Trust'),
    ('trust21', 'Calderdale and Huddersfield NHS Foundation Trust'),
    ('trust22', 'Cambridge University Hospitals NHS Foundation Trust'),
    ('trust23', 'Cambridgeshire and Peterborough NHS Foundation Trust'),
    ('trust24', 'Cambridgeshire Community Services NHS Trust'),
    ('trust25', 'Camden and Islington NHS Foundation Trust'),
    ('trust26', 'Central and North West London NHS Foundation Trust'),
    ('trust27', 'Central London Community Healthcare NHS Trust'),
    ('trust28', 'Chelsea and Westminster Hospital NHS Foundation Trust'),
    ('trust29', 'Cheshire and Wirral Partnership NHS Foundation Trust'),
    ('trust30', 'Chesterfield Royal Hospital NHS Foundation Trust'),
    ('trust31', 'The Christie NHS Foundation Trust'),
    ('trust32', 'Clatterbridge Cancer Centre NHS Foundation Trust'),
    ('trust33', 'Cornwall Partnership NHS Foundation Trust'),
    ('trust34', 'County Durham and Darlington NHS Foundation Trust'),
    ('trust35', 'Countess of Chester Hospital NHS Foundation Trust'),
    ('trust36', 'Coventry and Warwickshire Partnership NHS Trust'),
    ('trust37', 'Croydon Health Services NHS Trust'),
    ('trust38', 'Dartford and Gravesham NHS Trust'),
    ('trust39', 'Derbyshire Community Health Services NHS Trust'),
    ('trust40', 'Derbyshire Healthcare NHS Foundation Trust'),
    ('trust41', 'Devon Partnership NHS Trust'),
    ('trust42', 'Doncaster and Bassetlaw Teaching Hospitals NHS Foundation Trust'),
    ('trust43', 'Dorset County Hospital NHS Foundation Trust'),
    ('trust44', 'Dorset HealthCare University NHS Foundation Trust'),
    ('trust45', 'Dudley and Walsall Mental Health Partnership NHS Trust'),
    ('trust46', 'Dudley Group NHS Foundation Trust'),
    ('trust47', 'East and North Hertfordshire NHS Trust'),
    ('trust48', 'East Cheshire NHS Trust'),
    ('trust49', 'East Kent Hospitals University NHS Foundation Trust'),
    ('trust50', 'East Lancashire Hospitals NHS Trust'),
    ('trust51', 'East London NHS Foundation Trust'),
    ('trust52', 'East Midlands Ambulance Service NHS Trust'),
    ('trust53', 'East of England Ambulance Service NHS Trust'),
    ('trust54', 'East Suffolk and North Essex NHS Foundation Trust'),
    ('trust55', 'East Sussex Healthcare NHS Trust'),
    ('trust56', 'Enfield Primary Care NHS Trust'),
    ('trust57', 'Epsom and St Helier University Hospitals NHS Trust'),
    ('trust58', 'Essex Partnership University NHS Foundation Trust'),
    ('trust59', 'Frimley Health NHS Foundation Trust'),
    ('trust60', 'Gateshead Health NHS Foundation Trust'),
    ('trust61', 'George Eliot Hospital NHS Trust'),
    ('trust62', 'Gloucestershire Health and Care NHS Foundation Trust'),
    ('trust63', 'Gloucestershire Hospitals NHS Foundation Trust'),
    ('trust64', 'Great Ormond Street Hospital for Children NHS Foundation Trust'),
    ('trust65', 'Great Western Hospitals NHS Foundation Trust'),
    ('trust66', 'Guy\'s and St Thomas\' NHS Foundation Trust'),
    ('trust67', 'Hampshire Hospitals NHS Foundation Trust'),
    ('trust68', 'Harrogate and District NHS Foundation Trust'),
    ('trust69', 'Hertfordshire Community NHS Trust'),
    ('trust70', 'Hertfordshire Partnership University NHS Foundation Trust'),
    ('trust71', 'Hillingdon Hospitals NHS Foundation Trust'),
    ('trust72', 'Homerton University Hospital NHS Foundation Trust'),
    ('trust73', 'Hounslow and Richmond Community Healthcare NHS Trust'),
    ('trust74', 'Hull University Teaching Hospitals NHS Trust'),
    ('trust75', 'Humber NHS Foundation Trust'),
    ('trust76', 'Imperial College Healthcare NHS Trust'),
    ('trust77', 'Isle of Wight NHS Trust'),
    ('trust78', 'James Paget University Hospitals NHS Foundation Trust'),
    ('trust79', 'Kent and Medway NHS and Social Care Partnership Trust'),
    ('trust80', 'Kent Community Health NHS Foundation Trust'),
    ('trust81', 'Kettering General Hospital NHS Foundation Trust'),
    ('trust82', 'King\'s College Hospital NHS Foundation Trust'),
    ('trust83', 'Kingston Hospital NHS Foundation Trust'),
    ('trust84', 'Lancashire Teaching Hospitals NHS Foundation Trust'),
    ('trust85', 'Lancashire and South Cumbria NHS Foundation Trust'),
    ('trust86', 'Leeds and York Partnership NHS Foundation Trust'),
    ('trust87', 'Leeds Community Healthcare NHS Trust'),
    ('trust88', 'Leeds Teaching Hospitals NHS Trust'),
    ('trust89', 'Leicestershire Partnership NHS Trust'),
    ('trust90', 'Lewisham and Greenwich NHS Trust'),
    ('trust91', 'Lincolnshire Community Health Services'),
    ('trust92', 'Lincolnshire Partnership NHS Foundation Trust'),
    ('trust93', 'Liverpool Community Health NHS Trust'),
    ('trust94', 'Liverpool Heart and Chest Hospital NHS Foundation Trust'),
    ('trust95', 'Liverpool University Hospitals NHS Foundation Trust'),
    ('trust96', 'Liverpool Women\'s NHS Foundation Trust'),
    ('trust97', 'London Ambulance Service NHS Trust'),
    ('trust98', 'London North West University Healthcare NHS Trust'),
    # Add more here in the same format as needed
]

MEDICAL_SPECIALTIES = [
    ('academic', 'Academic Medicine'),
    ('acute_med', 'Acute Internal Medicine'),
    ('anaesthetics', 'Anaesthetics'),
    ('bariatric_surg', 'Bariatric Surgery'),
    ('cardio', 'Cardiology'),
    ('cardiothoracic', 'Cardiothoracic Surgery'),
    ('clinical_genetics', 'Clinical Genetics'),
    ('clinical_pharma', 'Clinical Pharmacology and Therapeutics'),
    ('colorectal_surg', 'Colorectal Surgery'),
    ('community_repro_health', 'Community Sexual and Reproductive Health'),
    ('derm', 'Dermatology'),
    ('em', 'Emergency Medicine'),
    ('endo', 'Endocrinology'),
    ('ent', 'ENT'),
    ('forensic_path', 'Forensic Pathology'),
    ('gastro', 'Gastroenterology'),
    ('gen_surg', 'General Surgery'),
    ('geriatrics', 'Geriatric Medicine'),
    ('gp', 'GP'),
    ('haem', 'Haematology'),
    ('hand_surg', 'Hand Surgery'),
    ('hepatology', 'Hepatology'),
    ('hpbs', 'Hepatopancreatobiliary Surgery'),
    ('immuno', 'Immunology'),
    ('id', 'Infectious Diseases'),
    ('maxfax', 'Oral and Maxillofacial Surgery'),
    ('nephro', 'Nephrology'),
    ('neuro', 'Neurology'),
    ('neurosurg', 'Neurosurgery'),
    ('nuclear_med', 'Nuclear Medicine'),
    ('obgyn', 'Obstetrics and Gynaecology'),
    ('onco', 'Oncology'),
    ('ophtho', 'Ophthalmology'),
    ('ortho', 'Orthopaedics'),
    ('paeds', 'Paediatrics'),
    ('palliative', 'Palliative Medicine'),
    ('path', 'Pathology'),
    ('plastics', 'Plastic Surgery'),
    ('psych', 'Psychiatry'),
    ('public_health', 'Public Health Medicine'),
    ('radio', 'Radiology'),
    ('rehab', 'Rehabilitation Medicine'),
    ('resp', 'Respiratory Medicine'),
    ('rheum', 'Rheumatology'),
    ('sports_med', 'Sports and Exercise Medicine'),
    ('transplant_surg', 'Transplant Surgery'),
    ('trauma_surg', 'Trauma Surgery'),
    ('trop_med', 'Tropical Medicine'),
    ('urology', 'Urology'),
    ('vascular', 'Vascular Surgery'),
]

# Year configuration
CURRENT_YEAR = datetime.now().year
YEARS = [(str(year), str(year)) for year in range(2000, CURRENT_YEAR+1)]